### ISSUE TITLE
Module Version name

### ISSUE THREAD

**Issue by AlexAgo83** [dealt-services/dealt-prestashop-module#1]
Hello, le module en version 0.0.4 affiche 0.0.3 sur la plateform de mise à jour des modules.
En creusant je vois que le config.xml indique toujours 0.0.3, hors le tag/release indique 0.0.4 sur ce package.

**Comment by AlexAgo83** [comment]
lien vers le config.xml en question : https://github.com/dealt-services/dealt-prestashop-module/blob/master/config.xml

**Comment by edvincandon** [comment]
fixed in v0.0.4 release
